// ------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Версия среды выполнения: 15.0.0.0
//  
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Yamly.UnityEditor
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Yamly.Proxy;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    internal partial class StorageGenerator : ProxyCodeGenerator
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
Initialize();
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 8 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    public void WriteStorageType(RootDefinition root)
    {
        var storageTypeName = GetStorageTypeName(root);

        
        #line default
        #line hidden
        
        #line 12 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("    public sealed class ");

        
        #line default
        #line hidden
        
        #line 13 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(storageTypeName));

        
        #line default
        #line hidden
        
        #line 13 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("\r\n\t    : StorageBase\r\n\t{\r\n\t    public ");

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(storageTypeName));

        
        #line default
        #line hidden
        
        #line 16 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("()\r\n\t\t{\r\n\t\t    Group = \"");

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(root.Group));

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("\";\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 20 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

        
        var attribute = root.Root.GetSingle<ConfigDeclarationAttributeBase>();
        if (attribute is SingleConfig)
        {
            SingleTypeContent(root);
        } 
        else if (attribute is ConfigList)
        {
            ListTypeContent(root);
        }
		else if (attribute is ConfigDictionary)
        {
            DictionaryTypeContent(root);
        }

        
        #line default
        #line hidden
        
        #line 35 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("    }\r\n");

        
        #line default
        #line hidden
        
        #line 37 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    }

    public void WriteUsings(IEnumerable<string> namespaces)
    {
        foreach (var ns in namespaces)
        {

        
        #line default
        #line hidden
        
        #line 44 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("using ");

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ns));

        
        #line default
        #line hidden
        
        #line 45 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(";\r\n");

        
        #line default
        #line hidden
        
        #line 46 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

        }
    }

    public void WriteNamespace(string ns, Action generateContent)
    {

        
        #line default
        #line hidden
        
        #line 52 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("namespace ");

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(ns));

        
        #line default
        #line hidden
        
        #line 53 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("\r\n{");

        
        #line default
        #line hidden
        
        #line 54 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

        generateContent();
        
        #line default
        #line hidden
        
        #line 55 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("}");

        
        #line default
        #line hidden
        
        #line 56 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    }

        
        #line default
        #line hidden
        
        #line 60 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    const string proxy = "_proxy";
    const string cache = "_cache";
    const string init = "_cached";    

        
        #line default
        #line hidden
        
        #line 66 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    private void SingleTypeContent(RootDefinition root)
    {
        var storageTypeName = GetStorageTypeName(root);
        var originTypeName = root.Root.Name;
        var proxyTypeName = GetProxyTypeName(root.Root);
        PrivateGenericFieldDeclaration(proxy, proxyTypeName, true);
        PrivateGenericFieldDeclaration(cache, originTypeName, false);

        
        #line default
        #line hidden
        
        #line 74 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("        public ");

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originTypeName));

        
        #line default
        #line hidden
        
        #line 75 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" Value\r\n\t\t{\r\n\t\t    get \r\n\t\t\t{ \r\n\t\t\t    if(!");

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 79 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(")\r\n\t\t\t\t{\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 81 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(";\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 82 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t\t}\r\n\t\t\t\r\n\t\t\t    return ");

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 85 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("; \r\n\t\t\t}\r\n\t\t\tset \r\n\t\t\t{ \r\n\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 89 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 89 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = value;\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 90 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 90 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = value;\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 91 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 91 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic static implicit operator ");

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originTypeName));

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(storageTypeName));

        
        #line default
        #line hidden
        
        #line 95 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" storage)\r\n\t\t{\r\n\t\t    return storage == null ? default(");

        
        #line default
        #line hidden
        
        #line 97 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originTypeName));

        
        #line default
        #line hidden
        
        #line 97 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(") : storage.Value;\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 99 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    }

        
        #line default
        #line hidden
        
        #line 103 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    private void ListTypeContent(RootDefinition root)
    {
        var storageTypeName = GetStorageTypeName(root);
        var originTypeName = root.Root.Name;
        var listOriginTypeName = GetListTypeName(originTypeName, false);
        var proxyTypeName = GetProxyTypeName(root.Root);
        var listProxyTypeName = GetListTypeName(proxyTypeName, true);
		PrivateGenericFieldDeclaration(proxy, listProxyTypeName, true);
        PrivateGenericFieldDeclaration(cache, listOriginTypeName, false);

        var listType = typeof(List<>).MakeGenericType(root.Root);

        var proxyToOrigin = GetTypeConversion(listType, proxy, false, false);
        var originToProxy = GetTypeConversion(listType, "value", true, true);

        
        #line default
        #line hidden
        
        #line 118 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("        public ");

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(listOriginTypeName));

        
        #line default
        #line hidden
        
        #line 119 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" Value\r\n\t\t{\r\n\t\t    get \r\n\t\t\t{ \r\n\t\t\t    if(!");

        
        #line default
        #line hidden
        
        #line 123 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 123 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(")\r\n\t\t\t\t{\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 125 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 125 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 125 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxyToOrigin));

        
        #line default
        #line hidden
        
        #line 125 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(";\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 126 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 126 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t\t}\r\n\t\t\t\r\n\t\t\t    return ");

        
        #line default
        #line hidden
        
        #line 129 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 129 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("; \r\n\t\t\t}\r\n\t\t\tset \r\n\t\t\t{ \r\n\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 133 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 133 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = ");

        
        #line default
        #line hidden
        
        #line 133 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originToProxy));

        
        #line default
        #line hidden
        
        #line 133 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(";\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 134 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 134 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = value;\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 135 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 135 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic static implicit operator ");

        
        #line default
        #line hidden
        
        #line 139 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(listOriginTypeName));

        
        #line default
        #line hidden
        
        #line 139 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 139 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(storageTypeName));

        
        #line default
        #line hidden
        
        #line 139 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" storage)\r\n\t\t{\r\n\t\t    return storage == null ? default(");

        
        #line default
        #line hidden
        
        #line 141 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(listOriginTypeName));

        
        #line default
        #line hidden
        
        #line 141 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(") : storage.Value;\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 143 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    }

        
        #line default
        #line hidden
        
        #line 147 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    private void DictionaryTypeContent(RootDefinition root)
    {
        var storageTypeName = GetStorageTypeName(root);
        var proxyTypeName = GetProxyTypeName(root.Root);

        var keyType = GetKeyType(root.Root);
        var valueType = root.Root;
        var dictionaryType = typeof(Dictionary<,>).MakeGenericType(keyType, valueType);
		var dictionaryTypeName = GetDictionaryTypeName(keyType.Name, valueType.Name);

		PrivateGenericFieldDeclaration($"{proxy}Keys", $"{GetProxyTypeName(keyType)}[]", true);
		PrivateGenericFieldDeclaration($"{proxy}Values", $"{GetProxyTypeName(valueType)}[]", true);
        PrivateGenericFieldDeclaration(cache, GetDictionaryTypeName(keyType.Name, valueType.Name), false);

        var originToProxyKey = GetTypeConversion(keyType, "k", false, false);
        var originToProxyValue = GetTypeConversion(valueType, "v", false, false);
        var proxyToOriginKey = GetTypeConversion(keyType, "value", true, true);
        var proxyToOriginValue = GetTypeConversion(valueType, "value", true, true);

        
        #line default
        #line hidden
        
        #line 166 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("        public ");

        
        #line default
        #line hidden
        
        #line 167 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryTypeName));

        
        #line default
        #line hidden
        
        #line 167 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" Value\r\n\t\t{\r\n\t\t    get \r\n\t\t\t{ \r\n\t\t\t    if(!");

        
        #line default
        #line hidden
        
        #line 171 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 171 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(")\r\n\t\t\t\t{\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = SerializationUtility.Convert(");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("Keys, ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("Values, key => ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxyToOriginKey));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(", value => ");

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxyToOriginValue));

        
        #line default
        #line hidden
        
        #line 173 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(");\r\n\t\t\t\t    ");

        
        #line default
        #line hidden
        
        #line 174 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 174 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t\t}\r\n\t\t\t\r\n\t\t\t    return ");

        
        #line default
        #line hidden
        
        #line 177 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 177 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("; \r\n\t\t\t}\r\n\t\t\tset \r\n\t\t\t{ \r\n\t\t\t    SerializationUtility.Convert(value, k => ");

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originToProxyKey));

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(", v => ");

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(originToProxyValue));

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(", out ");

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("Keys, out ");

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(proxy));

        
        #line default
        #line hidden
        
        #line 181 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("Values);\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 182 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(cache));

        
        #line default
        #line hidden
        
        #line 182 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = value;\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 183 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(init));

        
        #line default
        #line hidden
        
        #line 183 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" = true;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic static implicit operator ");

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryTypeName));

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write("(");

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(storageTypeName));

        
        #line default
        #line hidden
        
        #line 187 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(" storage)\r\n\t\t{\r\n\t\t    return storage == null ? default(");

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(dictionaryTypeName));

        
        #line default
        #line hidden
        
        #line 189 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"
this.Write(") : storage.Value;\r\n\t\t}\r\n");

        
        #line default
        #line hidden
        
        #line 191 "C:\Users\0bogg\Documents\Boggart\Yamly\Yamly.Generate.Unity\StorageGenerator.tt"

    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
